name: firebase_emilator_1
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #firebase depednecises 
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  cloud_firestore: ^4.9.3

  cupertino_icons: ^1.0.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
#added this on suggesion from bard to make the actial device commnection work not sure if it is need
# with or wihtout this the virtual device set up is working on emulator
firebase:
  options:
    core:
      emulator: true
      emulators:
        firestore: 8080